// Frontend/todovue/src/components/TodoCard.vue
<template>
  <div id="todoCard">
    <div v-if="!editing">
        <h3>{{ todo.title }}</h3>
        <p>{{ todo.context }}</p>
        <button @click="togleEdit">Edit</button>
        <button @click="onDelete">Delete</button>
    </div>
    
    
    <form v-if="editing" @submit.prevent="submitEdit">
        <label>
            title
            <input type="text" id="title" v-model="editTitle">
        </label>
        <label>
            context
            <input type="text" id="context" v-model="editContext">
        </label>
        <button type="submit">Submit</button>
    </form>
    
  </div>
</template>

<script>

export default {
  name: 'TodoCard',

  data(){
    return{
      editing: false,
      editTitle: '',
      editContext: ''
    }
  },

  props: {
    todo: {
        type: Object
    }
  },

  methods: {
    togleEdit(){
        this.editing = !this.editing;
        if (this.editing) {
          this.editTitle = this.todo.title;
          this.editContext = this.todo.context;
        }
    },
    submitEdit(){
        this.$emit('update', {
          ...this.todo,
          title: this.editTitle,
          context: this.editContext
        });
        this.editing = false;
    },
    onDelete(){
        this.$emit('delete', this.todo.id);
    },
    ondelete(){
        this.$emit('delete', this.todo.id);
    }
  },

  mounted(){
  }
}
</script>

<style>

</style>

// Frontend/todosvelte/src/TodoCard.svelte
<script>
	export let editing = false;
    export let todo;
    export let onUpdate 
    export let onDelete 

    export let editTitle = todo.title
    export let editContext = todo.context

    const togleEditing = () => {
        editing = !editing;
    }

    const onEdit = () => {
        onUpdate({
            id: todo.id,
            title: editTitle,
            context: editContext
        })
        togleEditing()
    }

    const onDeleteTodo = () => {
        onDelete(todo.id);
    }
</script>

<main>
    {#if !editing}
        <div>
            <h3>{todo.title}</h3>
            <p>{todo.context}</p>
            <button on:click={togleEditing}>Edit</button>
            <button on:click={onDeleteTodo}>Delete</button>
        </div>
    
    {:else}
        <form on:submit={onEdit}>
            <label>
                title
                <input type="text" bind:value={editTitle}>
            </label>
            <label>
                context
                <input type="text" bind:value={editContext}>
            </label>
            <button type="submit">Submit</button>
        </form>
    {/if}
</main>

<style>

</style>
